# Generated by Django 2.0.2 on 2018-02-08 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AwardAndCertification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_or_certification', models.CharField(max_length=128, verbose_name='获奖情况及证书')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='校名')),
                ('academic', models.CharField(choices=[('1', '高中'), ('2', '大专'), ('3', '本科')], max_length=128, verbose_name='学历')),
                ('major', models.CharField(max_length=128, verbose_name='专业')),
                ('start_data', models.DateField(verbose_name='起始时间')),
                ('end_data', models.DateField(default='至今', verbose_name='结束时间')),
                ('mark', models.CharField(blank=True, max_length=128, verbose_name='成绩')),
            ],
            options={
                'verbose_name': '教育经历',
                'verbose_name_plural': '教育经历',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=128, verbose_name='公司名')),
                ('position', models.CharField(max_length=128, verbose_name='职位')),
                ('content', models.TextField(verbose_name='内容')),
                ('start_data', models.DateField(verbose_name='起始时间')),
                ('end_data', models.DateField(default='至今', verbose_name='结束时间')),
            ],
            options={
                'verbose_name': '工作经历',
                'verbose_name_plural': '工作经历',
            },
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.TextField(max_length=128, verbose_name='兴趣爱好')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=128, verbose_name='技能')),
                ('content', models.TextField(verbose_name='内容')),
            ],
            options={
                'verbose_name': '掌握技能',
                'verbose_name_plural': '掌握技能',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=128, verbose_name='用户名')),
                ('name', models.CharField(max_length=128, verbose_name='姓名')),
                ('address', models.CharField(max_length=256, verbose_name='地址')),
                ('number', models.CharField(max_length=128, verbose_name='联系方式')),
                ('email', models.CharField(max_length=128, verbose_name='邮箱')),
                ('sample_intro', models.TextField(verbose_name='简介')),
                ('Facebook_account', models.CharField(blank=True, max_length=128, verbose_name='Facebook账号')),
                ('Twitter_account', models.CharField(blank=True, max_length=128, verbose_name='Twitter账号')),
                ('Ins_account', models.CharField(blank=True, max_length=128, verbose_name='Ins账号')),
                ('Github_account', models.CharField(blank=True, max_length=128, verbose_name='GitHub账号')),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
        migrations.AddField(
            model_name='skill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.User', verbose_name='姓名'),
        ),
        migrations.AddField(
            model_name='interest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.User', verbose_name='姓名'),
        ),
        migrations.AddField(
            model_name='experience',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.User', verbose_name='姓名'),
        ),
        migrations.AddField(
            model_name='education',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.User', verbose_name='姓名'),
        ),
        migrations.AddField(
            model_name='awardandcertification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.User', verbose_name='姓名'),
        ),
    ]
