# Generated by Django 2.0.2 on 2018-02-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='awardandcertification',
            options={'verbose_name': '获奖及证书', 'verbose_name_plural': '获奖及证书'},
        ),
        migrations.AlterModelOptions(
            name='interest',
            options={'verbose_name': '兴趣爱好', 'verbose_name_plural': '兴趣爱好'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': '工作技能', 'verbose_name_plural': '工作技能'},
        ),
        migrations.AlterField(
            model_name='awardandcertification',
            name='award_or_certification',
            field=models.TextField(max_length=128, verbose_name='获奖情况及证书'),
        ),
    ]
