# Generated by Django 2.0.2 on 2018-02-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20180208_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awardandcertification',
            name='award_or_certification',
            field=models.CharField(max_length=128, verbose_name='获奖情况及证书'),
        ),
    ]
