# Generated by Django 2.0.2 on 2018-02-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20180208_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='academic',
            field=models.CharField(choices=[('高中', '高中'), ('大专', '大专'), ('本科', '本科')], max_length=128, verbose_name='学历'),
        ),
    ]
