# Generated by Django 2.0.2 on 2018-02-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20180208_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='interest',
            field=models.TextField(verbose_name='兴趣爱好'),
        ),
    ]
